### ISSUE TITLE
Only download new videos from channel + filter

### ISSUE THREAD

**Issue by shakeyourbunny** [Tyrrrz/YoutubeDownloader#100]
It would be REALLY greate if the YoutubeDownloader would be able to download only newer videos of a given channel.

In addition, add a (list of ) filters for only/not downloading videos by title.

**Comment by Tyrrrz** [comment]
You can choose which videos you want to download.

As for the second part, I don't understand what you mean.

**Comment by shakeyourbunny** [comment]
Well, I thought it would be neat, if you give the downloader a channel url like https://www.youtube.com/channel/UCFhGP_J_TxhkAdKXR78QZsA. On the first run, it grabs all videos which are not filtered out (see below). On the second and the following run it gets only these which are not present in the download directory, without needing to manually select them.

I meant with the second part that you can make some filters (one per line). These are applied to the list of video titles in the download list and automatically deselect all items where they match.

So, lets say you have the filters "live" and "stream", the video list is:
- Review of Shootinator 2000
- Livestream of Chicken and Eggs  (both terms match)
- My streaming session with World of Tanks ("stream" matches) 
- Review of Reversi

If you hit download, just both Review videos are downloaded and the others will be ignored.

**Comment by MattWing1510** [comment]
> Well, I thought it would be neat, if you give the downloader a channel url like https://www.youtube.com/channel/UCFhGP_J_TxhkAdKXR78QZsA. On the first run, it grabs all videos which are not filtered out (see below). On the second and the following run it gets only these which are not present in the download directory, without needing to manually select them.
> 
> I meant with the second part that you can make some filters (one per line). These are applied to the list of video titles in the download list and automatically deselect all items where they match.
> 
> So, lets say you have the filters "live" and "stream", the video list is:
> 
> * Review of Shootinator 2000
> * Livestream of Chicken and Eggs  (both terms match)
> * My streaming session with World of Tanks ("stream" matches)
> * Review of Reversi
> 
> If you hit download, just both Review videos are downloaded and the others will be ignored.

Sounds like you are referring to something like Youtube-DL does witht he "archive" parameter. I this case the programm protocols all checked/downloaded videos and write the ID of the video in an .txt/.md file (you specify) and ignore that video if it's in that list. The Title-Name checker could be done with the RegEx parameter in that software.

When this sounds like kind of you need, you may give that software a try.

What I would really like to have in @Tyrrrz piece of software is an parameter where I can say "show only n videos per request" when I enter an youtube channel. So that the software don't need to fetch all videos from that channel (which needs some time and the program may freeze) and only fetch the latest. This could take advantage of the really great look up algorithm (which he used instead of the YouTube API v3 which needs Quota).

I would be really thankfull if that could be implemented.

**Comment by Tyrrrz** [comment]
Descoping this as it's likely not ever going to get implemented.
