### ISSUE TITLE
Error: The given key was not present in the dictionary

### ISSUE THREAD

**Issue by Hunanbean** [Tyrrrz/YoutubeDownloader#146]
Error: The given key was not present in the dictionary

specifically at this video url

https://www.youtube.com/watch?v=U9l9RL9ivw4

Thank you

**Comment by mustafacagataytulun** [comment]
@Hunanbean I cannot reproduce this error with version 1.7.14 by using the video you have specified. Could you please add a screenshot of the error, and also could you please add a screenshot of the Settings window of YoutubeDownloader? I will try to reproduce the bug with your settings and steps.

**Comment by Hunanbean** [comment]
Although the download is still failing almost instatly, i cannot get the screen where the error message was.
![ScreenShot3](https://user-images.githubusercontent.com/52123900/96929076-69dd4900-146e-11eb-8a16-913017dfce65.jpg)
![ScreenShot4](https://user-images.githubusercontent.com/52123900/96929083-6d70d000-146e-11eb-92d3-79ec28566914.jpg)
![ScreenShot7](https://user-images.githubusercontent.com/52123900/96929089-706bc080-146e-11eb-8f6a-ef3c8385a545.jpg)

Thank you

**Comment by mustafacagataytulun** [comment]
@Tyrrrz I examined this issue. It seems that when we get stream info for this specific video in YoutubeExplode and get contentLength here (GetManifestAsync method of StreamClient):

![image](https://user-images.githubusercontent.com/2426207/97027332-3fb98300-1563-11eb-930a-a2bf6e493249.png)

the HEAD request to the 720p URL returns a content length of 32384770. But when we actually try to download the video, it doesn't return any content.

I double-checked the HEAD request with Postman, and yes, the content length is indeed that number.

I also tried the same URL in Firefox to download the video, and got an error:

![image](https://user-images.githubusercontent.com/2426207/97027582-9c1ca280-1563-11eb-946f-aaf9b4acd7eb.png)

I sense something fishy on Youtube side, but cannot proceed any further, since I'm not really an expert on Youtube's inner working.

This could be an issue with muxed streams that you mentioned here: https://github.com/Tyrrrz/YoutubeExplode/issues/159#issuecomment-491615103

I write my findings here in the hope that they provide you with some headstart and shorten your time spent on this issue.

**Comment by Tyrrrz** [comment]
@beawolf what you are describing is most likely an unrelated issue and unfortunately one we can't really deal with since it's probably an error on YouTube's side.

The original issue is caused by https://github.com/Tyrrrz/YoutubeExplode/issues/461.

**Comment by Jeager2** [comment]
Here is how I resolved it... This may help you...

using YoutubeExplode;
using YoutubeExplode.Converter;
var youtube = new YoutubeClient();


// This line is the correct line: (EX2)
await youtube.Videos.DownloadAsync("https://youtu.be/rQb7aIBuTvA", "video.mp4");

// if you download like this it now fails but used to work before: (EX1)
string ID = "rQb7aIBuTvA";
await youtube.Videos.DownloadAsync(ID, "video.mp4");

I also had this issue and upon changing this line and testing back and forth it continued to fail in EX1 and pass in EX2.

I agree with Tyrrrz that it sounds like something on youtubes side but this has worked since I put it in place.

**Comment by zjjohncq** [comment]
I used the following for download which is not use the ID or url, and at my side, there is no client.Videos.DownloadAsync method, did I have some wrong version?
var result = client.Videos.Streams.DownloadAsync(streamInfo, _downloadingFileName, _bar, cancelToken.Token);

**Comment by Tyrrrz** [comment]
@Jeager2 using URL in place of ID or vice-versa should really have no impact, as it gets parsed down to ID in the end anyway.
@zjjohncq that's provided by [YoutubeExplode.Converter](https://github.com/Tyrrrz/YoutubeExplode.Converter).
