### ISSUE TITLE
Only download a certain duration of the media

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [Tyrrrz/YoutubeDownloader#163]
This will be great for users who only want a short part of content in a long video

**Comment by q7z** [comment]
I would like to bump this request. If this is put, it would set it apart from any other youtuber downloader. For instance the Youtube-dl GUI doesn't provide this functionality.

**Comment by lucidBrot** [comment]
In the same vein, it would be nice to have an option for downloading the sections of a video seperately. E.g. chapters of a tutorial, or single songs in an album that was uploaded as a single video. I don't know how well-accessible that information is through the API, but it does exist on the website.

Example:  
![image](https://user-images.githubusercontent.com/4920691/111622358-5ea60380-87e9-11eb-9c47-fac10afe62b3.png)
e.g. [this video](https://www.youtube.com/watch?v=tko9XqWgT30)

**Comment by guido-visser** [comment]
I second this request. It would be very beneficial :)

**Comment by Tyrrrz** [comment]
Sorry for (very) late reply, but I decided to put the project into maintenance mode due to shifting priorities so it unfortunately won't be receiving new features.

**Comment by q7z** [comment]
Awww, could this be the very very last feature you add to this project, the parting gift. The mark  of an end of an era? Is it a trivial addition?

**Comment by lucidBrot** [comment]
@guido-visser @q7z I have in the meantime [found a different project](https://twitter.com/LucidBrot/status/1379168932741910537?s=20) that supports exactly this feature. 

It's a [fork of youtube-dl](https://github.com/yt-dlp/yt-dlp#new-features) which has many additional features, and can be used for downloading "chapterized" audios like I wanted to by doing
```bash
yt-dlp --split-chapters -x THE_URL
```

@Tyrrrz Don't worry, I get that. Maintaining projects and adding features you don't even want to use yourself is not something we can expect for free if you don't feel like it :heart:

**Comment by q7z** [comment]
@lucidBrot Thanks for this I'll try working around. I totally agree with you on that part, @Tyrrrz how difficult do you think it would be to add this? I am willing to first sponsor the addition of this feature for what amount you reckon it should be.

**Comment by Tyrrrz** [comment]
> how difficult do you think it would be to add this? I am willing to first sponsor the addition of this feature for what amount you reckon it should be.

Thanks a lot for this suggestion, but it's not something money can fix unfortunately. I'm just trying to limit my exposure to projects I'm no longer as interested or motivated to work on, for the sake of my mental health. I love open source, but it can be really straining at times and lately it's becoming harder for me to deal with everything (it's not anyone's fault or anything, just the nature of things).

On top of that, I want users to have adequate expectations of the project's future. Of course, if anyone wants, they can make a fork and carry on from there, or just use any of the alternative solutions available (youtube-dl being the most popular one). And just to be clear, I will still be fixing bugs and YouTube breakages at my own pace because I'm also using this app myself, but new features won't be worked on.

**Comment by Pythonic-Rainbow** [comment]
thank you very much Tyrrrz, your work is still appreciated to this day!

**Comment by q7z** [comment]
Understandable, thank you and I really hope things improve for you!
