### ISSUE TITLE
Downloads hanging Issue

### ISSUE THREAD

**Issue by petermai6655** [Tyrrrz/YoutubeDownloader#172]
I'm experiencing issues where the download would get stuck after some time and not continue downloading unless I cancel and restart the download.

**Comment by akosinok** [comment]
hi im also experiencing this issue

**Comment by Acromatic** [comment]
Well lets see I just built it using the zip file and Microsoft Visual Studio Community 2019
Version 16.8.4
Which I think I got from unity but I did install personal version before that.
working fine... update your tools

**Comment by Acromatic** [comment]
Use the visual studio version selector, let it import (creates a backup anyway and you can just use this repo) after import it wanted .NET Framework SDK or whatever.. works without error or flaw here

**Comment by Acromatic** [comment]
Provide me a test video please and I'll try to replicate... the video code will be sufficient

**Comment by Acromatic** [comment]
Ok so my previous comment was about exploder, now I'm using downloader and I see the default maximum value for concurrent downloads is 2, so if you're doing more clearly it's not made to be that robust,... next thing is if you right-click on a download it gives you the option to restart them. Also are you manually adding these or using a playlist? I would use playlist or enable option to skip videos you have and right-click to restart

**Comment by Tyrrrz** [comment]
> I'm experiencing issues where the download would get stuck after some time and not continue downloading unless I cancel and restart the download.

Are you downloading a single video or multiple videos? By default only 2 downloads can run at a time.

**Comment by Acromatic** [comment]
That's just it, it's not a real issue. The reason they fail is because this uses .NET for downloading, and historically microsoft doesn't do concurrent downloading well, that's because it's more efficient for your typical user to have a minimal download, and to queue those downloads as you'll notice ALL microsoft software will adhere to. The internal connections to external sources in windows used to be like 10 or some low number, I've used many third party tools in the past to break free of those limitations but I try to stay as close to 100% legal as I can these days. Since I technically work in the computer industry it doesn't help to have "dirt" laying around and it's just more work for me to extend my natural installations (more is worse) in the case of modern computing. Singular or Dual streamlined workflows are more ideal and prefered. Like I've said in my previous post here, use only 2 as suggested or a playlist, if you must do more and it's failing than use the provided settings. The only internal fix for this would be a download queue system, and frankly if you want to make a downloader you may as well simulate a torrent downloader-like gui environment because the download queue system will work nicely.
