### ISSUE TITLE
I use proxy and It can download,but have problem

### ISSUE THREAD

**Issue by HuiProject** [Tyrrrz/YoutubeDownloader#18]
If I close there error window,the software will shutdown,
else I don't close these error window and the video can download.

![QQ截图20190507123206](https://user-images.githubusercontent.com/22783500/57272276-a1630480-70c5-11e9-9ce5-67df2a16c818.png)

**Comment by Tyrrrz** [comment]
Does this still happen with new version?

**Comment by HuiProject** [comment]
![D2 _7CT6WI3(M2X%8Q_2Z_M](https://user-images.githubusercontent.com/22783500/58706333-58f8e700-83e4-11e9-94e9-28b627d82f1e.png)
Maybe I download playlists can't work.

**Comment by Tyrrrz** [comment]
Can you give me playlist URL?

**Comment by M3nti0nL3Ss** [comment]
It's about the catch exceptions in the RootViewModel.cs .. 
`if (download.DownloadOption == null)

            {

                download.DownloadOption =

                    await _downloadService.GetBestDownloadOptionAsync(download.Video.Id, download.Format);

            }`
this part has to be puted in a try-catch exception

-2
`// Download

            try

            {

                await _downloadService.DownloadVideoAsync(download.DownloadOption, download.FilePath,

                    download.ProgressOperation, download.CancellationToken);

            }

            catch (OperationCanceledException)

            {

                // Ignore cancellations

            }` 
the exception has to be a global exception 

`// Download
            try
            {
                await _downloadService.DownloadVideoAsync(download.DownloadOption, download.FilePath,
                    download.ProgressOperation, download.CancellationToken);
                downloadCompleted = true;

            }
            catch (Exception e)
            {
                MessageBox.Show("Err2: "+e.Message);
                downloadCompleted = false;
            }

            if (downloadCompleted)
            {
                // Mark download as completed
                download.MarkAsCompleted();
            }
            else
            {
                download.Cancel();
            }`

I puted a boolean variable to check if the download hasn't any error .. then if something's wrong the download gonna be canceled .. (for a temporal solution)

3-
also the processQuery() methed has a try statement without a catch Exception so it has to have it in order to specify the error if the download's break

So by those modifications .. the program gonna avoid automatic closing after show any error .. also the OnUnhadlerException gonna be avoided ….
