### ISSUE TITLE
Downloading mp3 always choose bit-rate 124kbps

### ISSUE THREAD

**Issue by mrnams** [Tyrrrz/YoutubeDownloader#23]
Downloading mp3 always choose bit-rate 124kbps, there should be option to select bit-rate or default MUST be highest available.

**Comment by Tyrrrz** [comment]
The audio stream is chosen at the highest bitrate. Related to #13.

**Comment by mrnams** [comment]
@Tyrrrz I tried downloading mp3 of one of video and it downloaded with bitrate 124kbps, from same video I downloaded using browser extension and extension could download audio with bitrate 320kbps.
I tried debugging but could not understand values whether they are in bits/bytes...

**Comment by Tyrrrz** [comment]
Hm. I'll take a look. Can you give me a link to the video that you managed to download at 320kbps?

**Comment by mrnams** [comment]
@Tyrrrz  I forgot video I tried, but Please check below video and debug (its 192kbps)
https://www.youtube.com/watch?v=OMyeNoqtEdM

Using below site I could download mp3 in 192kbps bitrate
https://www.flvto.biz/

**Comment by mrnams** [comment]
@Tyrrrz did you reproduce issue?

**Comment by Tyrrrz** [comment]
Yes. The highest audio stream that YouTube offers for this videos is 128kbps m4a, flvto.biz most likely re-encodes it with a higher bitrate.

**Comment by mrnams** [comment]
But even for 4k video it shows 124kbps bitrate.
I feel something wrong data is getting supplied to YouTube api.
How it's possible that YouTube has highest bitrate 124kbpa for all videos?

**Comment by Tyrrrz** [comment]
No idea but I found this article: https://appuals.com/why-converting-youtube-to-320kbps-mp3-is-a-waste-of-time/

**Comment by mrnams** [comment]
@Tyrrrz  try below video
https://www.youtube.com/watch?v=YqeW9_5kURI
I downloaded audio using "4K YouTube to MP3" and with quality option to Original and it downloaded in 192kbps.

**Comment by Tyrrrz** [comment]
I see they go up to 143kbp/s

**Comment by avengerx** [comment]
I think this issue is actually quite actual. But it's really hard to measure. If you open a video in YouTube and "stats for nerds", it shows its audio coded and a code that specifies its bitrate. Most videos seems to report `opus (251)`. But then, what does that mean?

This gist offers a list of community-contributed "equivalence tables" for those codes: [DASH Audio - AgentOak/youtube_formats.md](https://gist.github.com/AgentOak/34d47c65b1d28829bb17c24c04a0096f#dash-audio)

Maybe this discussion adds up a bit of context: [Opus vs MP3 (Size & Quality Comparison) - Sound Stack Exchange](https://sound.stackexchange.com/questions/26167/opus-vs-mp3-size-quality-comparison)

Gathering the pieces, an "opus (251)" audio imbued to a YouTube video means Opus 128kbps variable bitrate (vbr). The problem is that this does not necessarily correspond to a MP3's bitrate, either 128kbps vbr or constant bitrate (cbr) output.

I've noticed the code forcibly specifies the MP3 bitrate to match the Opus one ([Tyrrr/YoutubeExplode@6.5.6:YoutubeExplode.Converter/Converter.cs:103-104](https://github.com/Tyrrrz/YoutubeExplode/blob/6.5.6/YoutubeExplode.Converter/Converter.cs#L103-L104)), or whichever format that is coming from, allegedly to avoid an issue with converting MP4 audio stream to MP3.

Furthermore, the `ffmpeg` tool has (at least since 2019, perhaps) means to infer better quality by itself while converting between formats. Instead of forcing a bitrate, one can `-q:a:<stream_id> 0` to set that audio track's "quality" to the best possible.

In fact, looking up ffmpeg documentation, I finally found what it means: [VBR Encoding - Encode/MP3 - ffmpeg](https://trac.ffmpeg.org/wiki/Encode/MP3#VBREncoding).

So, with the current `-b <bitrate>` setting, the MP3 is output forcibly as the same bitrate of the one reported by the opus codec in the Youtube video. This most likely is degrading the song, especially as it is turning the audio stream into constant bitrate.

I just went ahead then and chose the _quality_ setting (according to the documentation above) to be "best quality", or `-q:a:<stream> 0`.

I didn't do a hearing check, but by changing the lines linked above in Tyrrr/YoutubeExplode to:

```csharp
arguments.Add($"-q:a:{lastAudioStreamIndex++}").Add("0"); // Have ffmpeg determine best quality possible
```
(notice I removed the existing ones!)

I instantly got YoutubeDownloader to get better bitrate (variable) mp3 files.

As currently YoutubeDownloader is _degrading_ mp3 output quality, I'd suggest to deem this issue as a bug, reopen and (as the fix is so easy) fix this. I understand the project  is not getting "new features", right? :-)

If anyone outside the maintainers want to check this, and has Visual Studio / .NET 9 toolset installed here's a quick walkthru:

1. clone the [YoutubeExplode project](https://github.com/Tyrrrz/YoutubeExplode/)
2. open `YoutubeExplode.Converter/Converter.cs`
3. change the lines as stated above
4. build
5. open the project's `YoutubeExplode.Converter/bin/Debug/net9.0` folder (if you didn't change the configuration/target in Visual Studio)
6. ensure you have the YoutubeDownloader gui closed
7. copy over both `YoutubeExplode.Converter.dll` and `YoutubeExplode.dll` to the directory you installed YoutubeDownloader (backup the existing files beforehand).

From this point onwards, when downloading youtube videos as MP3, you'll let ffmpeg convert the (likely) opus 128k stream to the best vbr MP3 quality, losing the least in quality of the downloaded songs -- notice they will most likely take up more disk space, but I'd say it's not _considerably_ more, and worth it, in my opinion.
