### ISSUE TITLE
Hope to support resume

### ISSUE THREAD

**Issue by wwb7700** [Tyrrrz/YoutubeDownloader#316]
### Version

1.9.8

### Details

Hope to support resume

### Steps to reproduce

The network is interrupted and the download cannot continue

**Comment by Tyrrrz** [comment]
Resume is unsupported

**Comment by nestg** [comment]
Hope the same, I understand that resume feature only can be implemented when the server support this, but i think that can be some way to resume a yt stream. In my country the internet is very expensive and is the reason because i use this tool, when a large video file is disrupted and cant be resumed in my case is a money lost.
