### ISSUE TITLE
Crash while authenticating

### ISSUE THREAD

**Issue by CanePlayz** [Tyrrrz/YoutubeDownloader#351]
### Version

1.10.0

### Details

When I try to authenticate, this error message occurs once the WebView window gets closed:

![image](https://github.com/Tyrrrz/YoutubeDownloader/assets/81419612/760d4518-30b0-4a7a-b219-f7cd0c1b3dfa)

If I close that error message window, it pops up one more time and when I close that new window, the program crashes.

### Steps to reproduce

-Try to authenticate

**Comment by xBaank** [comment]
It also happens to me.
I think one fix could be to just get the cookies of `https://www.youtube.com` because it seems that `https://www.google.com` and `https://www.youtube.com` share somes cookies and they can't be mapped into a dictionary.

So instead of :
https://github.com/Tyrrrz/YoutubeDownloader/blob/e045cf0b315024d903cc003d9a349ffbd328ff8b/YoutubeDownloader/Views/Dialogs/AuthSetupView.xaml.cs#L63
Just get youtube cookies:
```
var cookies = await WebBrowser.CoreWebView2.CookieManager.GetCookiesAsync("https://www.youtube.com");
```
Other fix could be using the list of cookies directly instead of the dictionary mapping them from `WebView2Cookie` to `Cookie` like this:
```
ViewModel.Cookies = cookies.Select(i => i.ToSystemNetCookie())
```
And don't specify the domain in: 
https://github.com/Tyrrrz/YoutubeDownloader/blob/e045cf0b315024d903cc003d9a349ffbd328ff8b/YoutubeDownloader.Core/YoutubeAuthHttpHandler.cs#L21

as the cookies already have the domain information.

**Comment by Tyrrrz** [comment]
Thanks guys, I'll check later today

**Comment by ScottsplaysSus** [comment]
Same issue here, hope it can be fixed :)

![image](https://github.com/Tyrrrz/YoutubeDownloader/assets/91255736/c64c927c-a2da-4c2d-bb31-a36fe0d785d6)
![image](https://github.com/Tyrrrz/YoutubeDownloader/assets/91255736/f51c196d-958e-4f4f-b88d-704386881f52)

**Comment by Tyrrrz** [comment]
This is fixed. You might have to delete your `Settings.dat` file if you run into exceptions during startup (shouldn't happen though).
