### ISSUE TITLE
Error when try to download video in private playlist

### ISSUE THREAD

**Issue by reactioncs** [Tyrrrz/YoutubeDownloader#382]
### Version

v1.10.4

### Platform

Windows 11

### Steps to reproduce

Open public video in your private playlist, the url would be something like this:
`https://www.youtube.com/watch?v=VVV&list=LLL&index=1`
When try to download this, there will be error:
`Playlist 'LLL' is not available.`
I did not log into my account in the software.

### Details

if I delete the `list` and `index` query, the video can be downloaded normally.

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by Tyrrrz** [comment]
When you copy a link that includes `list=` the URL is parsed as a playlist URL, this is by design. It's the only way to ensure that the most specific intent is preserved -- i.e. when the user wants to download a playlist, they can do that, but if they want to download a video, they can just remove the other parameters from the URL. If the change from your PR is applied, then there would be no way to download playlists.
