### ISSUE TITLE
BindableCollection Insert issue

### ISSUE THREAD

**Issue by TheProxyRE** [Tyrrrz/YoutubeDownloader#5]
In RootViewModel.cs on AddDownload method

Downloads.Insert(index, download); line fails on large playlists 
quick fix is just to always insert on 0 but i doubt that is best solution

here is example large playlist if you want to play with it a bit: https://www.youtube.com/playlist?list=PL5ezn3MwwSNFNxyCiWYpJ0bx905ui-x-r

**Comment by Tyrrrz** [comment]
This approach was made so that multiple videos are added to the top with order preserved. It looks like index becomes out of bounds because there are 2 videos with identical autogenerated file paths, so one of the `AddDownload` calls overwrites a download instead of adding a new one, which causes the index to become invalid.

I will have to look into it...

**Comment by Tyrrrz** [comment]
This approach was made so that multiple videos are added to the top with order preserved. It looks like index becomes out of bounds because there are 2 videos with identical autogenerated file paths, so one of the `AddDownload` calls overwrites a download instead of adding a new one, which causes the index to become invalid.

I will have to look into it...
